START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS db_mobile_phones DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE db_mobile_phones;

DROP TABLE IF EXISTS table_mobile_phones;
CREATE TABLE table_mobile_phones (
  id int(11) NOT NULL,
  brand varchar(100) NOT NULL,
  model varchar(255) NOT NULL,
  os varchar(255) NOT NULL,
  memory int(11) NOT NULL,
  price decimal(6,2) NOT NULL,
  deal text NOT NULL,
  technology text NOT NULL,
  photo varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE table_mobile_phones
  ADD PRIMARY KEY (id);


ALTER TABLE table_mobile_phones
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
