# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_registrar.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(200, 10, 400, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titulo.sizePolicy().hasHeightForWidth())
        self.label_titulo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.lbl_modelo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_modelo.setGeometry(QtCore.QRect(150, 110, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_modelo.sizePolicy().hasHeightForWidth())
        self.lbl_modelo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.lbl_modelo.setFont(font)
        self.lbl_modelo.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lbl_modelo.setObjectName("lbl_modelo")
        self.txt_modelo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_modelo.setGeometry(QtCore.QRect(400, 110, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_modelo.sizePolicy().hasHeightForWidth())
        self.txt_modelo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.txt_modelo.setFont(font)
        self.txt_modelo.setObjectName("txt_modelo")
        self.lbl_sistema_operativo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sistema_operativo.setGeometry(QtCore.QRect(150, 150, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sistema_operativo.sizePolicy().hasHeightForWidth())
        self.lbl_sistema_operativo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.lbl_sistema_operativo.setFont(font)
        self.lbl_sistema_operativo.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lbl_sistema_operativo.setObjectName("lbl_sistema_operativo")
        self.txt_sistema_operativo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_sistema_operativo.setGeometry(QtCore.QRect(400, 150, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_sistema_operativo.sizePolicy().hasHeightForWidth())
        self.txt_sistema_operativo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.txt_sistema_operativo.setFont(font)
        self.txt_sistema_operativo.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_sistema_operativo.setObjectName("txt_sistema_operativo")
        self.lbl_memoria = QtWidgets.QLabel(self.centralwidget)
        self.lbl_memoria.setGeometry(QtCore.QRect(150, 190, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_memoria.sizePolicy().hasHeightForWidth())
        self.lbl_memoria.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_memoria.setFont(font)
        self.lbl_memoria.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lbl_memoria.setObjectName("lbl_memoria")
        self.txt_memoria = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_memoria.setGeometry(QtCore.QRect(400, 190, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_memoria.sizePolicy().hasHeightForWidth())
        self.txt_memoria.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_memoria.setFont(font)
        self.txt_memoria.setObjectName("txt_memoria")
        self.lbl_precio = QtWidgets.QLabel(self.centralwidget)
        self.lbl_precio.setGeometry(QtCore.QRect(150, 230, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_precio.sizePolicy().hasHeightForWidth())
        self.lbl_precio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_precio.setFont(font)
        self.lbl_precio.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lbl_precio.setObjectName("lbl_precio")
        self.txt_precio = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_precio.setGeometry(QtCore.QRect(400, 230, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_precio.sizePolicy().hasHeightForWidth())
        self.txt_precio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.txt_precio.setFont(font)
        self.txt_precio.setObjectName("txt_precio")
        self.btn_registrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_registrar.setGeometry(QtCore.QRect(300, 514, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_registrar.setFont(font)
        self.btn_registrar.setObjectName("btn_registrar")
        self.lbl_marca = QtWidgets.QLabel(self.centralwidget)
        self.lbl_marca.setGeometry(QtCore.QRect(150, 70, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_marca.sizePolicy().hasHeightForWidth())
        self.lbl_marca.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.lbl_marca.setFont(font)
        self.lbl_marca.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lbl_marca.setObjectName("lbl_marca")
        self.txt_marca = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_marca.setGeometry(QtCore.QRect(400, 70, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_marca.sizePolicy().hasHeightForWidth())
        self.txt_marca.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.txt_marca.setFont(font)
        self.txt_marca.setObjectName("txt_marca")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.menu_registrar = QtWidgets.QAction(MainWindow)
        self.menu_registrar.setObjectName("menu_registrar")
        self.menu_listar_text = QtWidgets.QAction(MainWindow)
        self.menu_listar_text.setObjectName("menu_listar_text")
        self.menu_salir = QtWidgets.QAction(MainWindow)
        self.menu_salir.setObjectName("menu_salir")
        self.menu_listar_list = QtWidgets.QAction(MainWindow)
        self.menu_listar_list.setObjectName("menu_listar_list")
        self.menu_listar_table = QtWidgets.QAction(MainWindow)
        self.menu_listar_table.setObjectName("menu_listar_table")
        self.menu.addAction(self.menu_registrar)
        self.menu.addAction(self.menu_listar_text)
        self.menu.addAction(self.menu_listar_list)
        self.menu.addAction(self.menu_listar_table)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_salir)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Móviles"))
        self.label_titulo.setText(_translate("MainWindow", "Registrar móvil"))
        self.lbl_modelo.setText(_translate("MainWindow", "Modelo:"))
        self.lbl_sistema_operativo.setText(_translate("MainWindow", "Sistema operativo:"))
        self.lbl_memoria.setText(_translate("MainWindow", "Memoria:"))
        self.lbl_precio.setText(_translate("MainWindow", "Precio:"))
        self.btn_registrar.setText(_translate("MainWindow", "Registrar"))
        self.lbl_marca.setText(_translate("MainWindow", "Marca:"))
        self.menu.setTitle(_translate("MainWindow", "Móviles"))
        self.menu_registrar.setText(_translate("MainWindow", "Registrar móvil"))
        self.menu_listar_text.setText(_translate("MainWindow", "Listar móviles (TextEdit)"))
        self.menu_salir.setText(_translate("MainWindow", "Salir"))
        self.menu_listar_list.setText(_translate("MainWindow", "Listar móviles (List Widget)"))
        self.menu_listar_table.setText(_translate("MainWindow", "Listar móviles (Table Widget)"))
