# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/window_update.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window_update(object):
    def setupUi(self, window_update):
        window_update.setObjectName("window_update")
        window_update.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(window_update.sizePolicy().hasHeightForWidth())
        window_update.setSizePolicy(sizePolicy)
        window_update.setMinimumSize(QtCore.QSize(800, 600))
        window_update.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        window_update.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\images/icons/icon_mobile_phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        window_update.setWindowIcon(icon)
        window_update.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(window_update)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(200, 10, 400, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_title.sizePolicy().hasHeightForWidth())
        self.lbl_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setUnderline(True)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_model = QtWidgets.QLabel(self.centralwidget)
        self.lbl_model.setGeometry(QtCore.QRect(150, 100, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_model.sizePolicy().hasHeightForWidth())
        self.lbl_model.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.lbl_model.setFont(font)
        self.lbl_model.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_model.setObjectName("lbl_model")
        self.txt_model = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_model.setGeometry(QtCore.QRect(405, 100, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_model.sizePolicy().hasHeightForWidth())
        self.txt_model.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.txt_model.setFont(font)
        self.txt_model.setStyleSheet("border-radius: 10px; border: 2px solid navy;")
        self.txt_model.setObjectName("txt_model")
        self.lbl_os = QtWidgets.QLabel(self.centralwidget)
        self.lbl_os.setGeometry(QtCore.QRect(150, 140, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_os.sizePolicy().hasHeightForWidth())
        self.lbl_os.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.lbl_os.setFont(font)
        self.lbl_os.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_os.setObjectName("lbl_os")
        self.lbl_memory = QtWidgets.QLabel(self.centralwidget)
        self.lbl_memory.setGeometry(QtCore.QRect(150, 180, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_memory.sizePolicy().hasHeightForWidth())
        self.lbl_memory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_memory.setFont(font)
        self.lbl_memory.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_memory.setObjectName("lbl_memory")
        self.txt_memory = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_memory.setGeometry(QtCore.QRect(405, 180, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_memory.sizePolicy().hasHeightForWidth())
        self.txt_memory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.txt_memory.setFont(font)
        self.txt_memory.setStyleSheet("border-radius: 10px; border: 2px solid navy;")
        self.txt_memory.setObjectName("txt_memory")
        self.lbl_price = QtWidgets.QLabel(self.centralwidget)
        self.lbl_price.setGeometry(QtCore.QRect(150, 220, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_price.sizePolicy().hasHeightForWidth())
        self.lbl_price.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_price.setFont(font)
        self.lbl_price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_price.setObjectName("lbl_price")
        self.txt_price = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_price.setGeometry(QtCore.QRect(405, 220, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_price.sizePolicy().hasHeightForWidth())
        self.txt_price.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.txt_price.setFont(font)
        self.txt_price.setStyleSheet("border-radius: 10px; border: 2px solid navy;")
        self.txt_price.setObjectName("txt_price")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(300, 514, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("background-color:lightblue; border-radius:20px; border:3px solid navy; color: black; font-family:Verdana; font-size:16px; font-weight:bold;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\images/icons/icon_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon1)
        self.btn_save.setIconSize(QtCore.QSize(32, 32))
        self.btn_save.setObjectName("btn_save")
        self.lbl_brand = QtWidgets.QLabel(self.centralwidget)
        self.lbl_brand.setGeometry(QtCore.QRect(150, 60, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_brand.sizePolicy().hasHeightForWidth())
        self.lbl_brand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.lbl_brand.setFont(font)
        self.lbl_brand.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_brand.setObjectName("lbl_brand")
        self.txt_brand = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_brand.setGeometry(QtCore.QRect(405, 60, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_brand.sizePolicy().hasHeightForWidth())
        self.txt_brand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.txt_brand.setFont(font)
        self.txt_brand.setStyleSheet("border-radius: 10px; border: 2px solid navy;")
        self.txt_brand.setObjectName("txt_brand")
        self.chk_deal = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_deal.setGeometry(QtCore.QRect(405, 260, 245, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.chk_deal.setFont(font)
        self.chk_deal.setText("")
        self.chk_deal.setObjectName("chk_deal")
        self.grp_technology = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_technology.setGeometry(QtCore.QRect(290, 300, 220, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grp_technology.setFont(font)
        self.grp_technology.setStyleSheet("border-radius: 10px; border: 2px solid navy;")
        self.grp_technology.setObjectName("grp_technology")
        self.rbtn_3g = QtWidgets.QRadioButton(self.grp_technology)
        self.rbtn_3g.setGeometry(QtCore.QRect(10, 30, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rbtn_3g.setFont(font)
        self.rbtn_3g.setStyleSheet("border: none;")
        self.rbtn_3g.setChecked(True)
        self.rbtn_3g.setObjectName("rbtn_3g")
        self.rbtn_4g = QtWidgets.QRadioButton(self.grp_technology)
        self.rbtn_4g.setGeometry(QtCore.QRect(80, 30, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rbtn_4g.setFont(font)
        self.rbtn_4g.setStyleSheet("border: none;")
        self.rbtn_4g.setObjectName("rbtn_4g")
        self.rbtn_5g = QtWidgets.QRadioButton(self.grp_technology)
        self.rbtn_5g.setGeometry(QtCore.QRect(150, 30, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rbtn_5g.setFont(font)
        self.rbtn_5g.setStyleSheet("border: none;")
        self.rbtn_5g.setObjectName("rbtn_5g")
        self.btn_select_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_select_image.setGeometry(QtCore.QRect(230, 380, 165, 110))
        self.btn_select_image.setStyleSheet("background-color:lightblue; border-radius:20px; border:3px solid navy; color: black; font-family:Verdana; font-size:16px; font-weight:bold;")
        self.btn_select_image.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_select_image.setFlat(False)
        self.btn_select_image.setObjectName("btn_select_image")
        self.lbl_deal = QtWidgets.QLabel(self.centralwidget)
        self.lbl_deal.setGeometry(QtCore.QRect(150, 260, 245, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_deal.sizePolicy().hasHeightForWidth())
        self.lbl_deal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_deal.setFont(font)
        self.lbl_deal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_deal.setObjectName("lbl_deal")
        self.lbl_image = QtWidgets.QLabel(self.centralwidget)
        self.lbl_image.setGeometry(QtCore.QRect(405, 380, 245, 110))
        self.lbl_image.setText("")
        self.lbl_image.setObjectName("lbl_image")
        self.cmb_os = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_os.setGeometry(QtCore.QRect(405, 140, 245, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.cmb_os.setFont(font)
        self.cmb_os.setStyleSheet("border-radius: 10px; border: 2px solid navy;")
        self.cmb_os.setObjectName("cmb_os")
        self.cmb_os.addItem("")
        self.cmb_os.addItem("")
        self.cmb_os.addItem("")
        self.cmb_os.addItem("")
        window_update.setCentralWidget(self.centralwidget)

        self.retranslateUi(window_update)
        QtCore.QMetaObject.connectSlotsByName(window_update)

    def retranslateUi(self, window_update):
        _translate = QtCore.QCoreApplication.translate
        window_update.setWindowTitle(_translate("window_update", "Móviles"))
        self.lbl_title.setText(_translate("window_update", "Modificar móvil"))
        self.lbl_model.setText(_translate("window_update", "Modelo:"))
        self.lbl_os.setText(_translate("window_update", "Sistema operativo:"))
        self.lbl_memory.setText(_translate("window_update", "Memoria:"))
        self.lbl_price.setText(_translate("window_update", "Precio:"))
        self.btn_save.setText(_translate("window_update", "Guardar"))
        self.lbl_brand.setText(_translate("window_update", "Marca:"))
        self.grp_technology.setTitle(_translate("window_update", "Tecnología"))
        self.rbtn_3g.setText(_translate("window_update", "3G"))
        self.rbtn_4g.setText(_translate("window_update", "4G"))
        self.rbtn_5g.setText(_translate("window_update", "5G"))
        self.btn_select_image.setText(_translate("window_update", "Seleccionar\n"
"imagen"))
        self.lbl_deal.setText(_translate("window_update", "Oferta:"))
        self.cmb_os.setItemText(0, _translate("window_update", "Android"))
        self.cmb_os.setItemText(1, _translate("window_update", "iOS"))
        self.cmb_os.setItemText(2, _translate("window_update", "Windows Phone"))
        self.cmb_os.setItemText(3, _translate("window_update", "Otro"))
